# Candela — generated by scripts/generate.js, do not edit.
# Offers to switch the UI theme to Adaptive when a Candela color scheme is active,
# so the sidebar, tabs and status bar follow the palette instead of staying gray.

import sublime
import sublime_plugin

ADAPTIVE = "Adaptive.sublime-theme"
PREFERENCES = "Preferences.sublime-settings"
STATE = "Candela.sublime-settings"


def _uses_candela(preferences):
    return "candela-" in preferences.get("color_scheme", "")


def _theme_follows_color_scheme(preferences):
    # "auto" resolves to light_theme/dark_theme, so check those instead.
    theme = preferences.get("theme", "auto")
    if theme != "auto":
        return theme == ADAPTIVE
    light = preferences.get("light_theme", "Default.sublime-theme")
    dark = preferences.get("dark_theme", "Default Dark.sublime-theme")
    return light == ADAPTIVE and dark == ADAPTIVE


def _use_adaptive():
    preferences = sublime.load_settings(PREFERENCES)
    preferences.set("theme", ADAPTIVE)
    sublime.save_settings(PREFERENCES)


def _offer_adaptive():
    preferences = sublime.load_settings(PREFERENCES)
    if not _uses_candela(preferences) or _theme_follows_color_scheme(preferences):
        return
    state = sublime.load_settings(STATE)
    if state.get("adaptive_prompt_answered", False):
        return
    # Recorded before the dialog so a crash or a force-quit mid-prompt cannot turn
    # the ask into a loop on every startup.
    state.set("adaptive_prompt_answered", True)
    sublime.save_settings(STATE)
    if sublime.ok_cancel_dialog(
        "Candela can also color the sidebar, tabs and status bar.\n\n"
        "That needs the Adaptive UI theme. Switch to it?",
        "Use Adaptive",
    ):
        _use_adaptive()


class CandelaUseAdaptiveUiCommand(sublime_plugin.ApplicationCommand):
    """Palette entry, so declining the prompt once is not permanent."""

    def run(self):
        _use_adaptive()

    def is_enabled(self):
        return not _theme_follows_color_scheme(sublime.load_settings(PREFERENCES))


def plugin_loaded():
    preferences = sublime.load_settings(PREFERENCES)
    preferences.add_on_change("candela_adaptive_ui", lambda: sublime.set_timeout(_offer_adaptive, 0))
    sublime.set_timeout(_offer_adaptive, 500)


def plugin_unloaded():
    sublime.load_settings(PREFERENCES).clear_on_change("candela_adaptive_ui")
